#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    appname: service-registry-cluster
#
#spring:
#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false
#  profiles:
#    active: singleserver
#
#
#---
#server:
#  port: 8761
#spring:
#  profiles: peer1
#eureka:
#  instance:
#    hostname: discovery-service-1
#    metadataMap:
#      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-service-1:8761/eureka/,http://discovery-service-2:8762/eureka/
#
#---
#server:
#  port: 8762
#spring:
#  profiles: peer2
#eureka:
#  instance:
#    hostname: discovery-service-2
#    metadataMap:
#      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-service-2:8762/eureka/,http://discovery-service-1:8761/eureka/

server:
  port: 8761

spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://localhost:8761
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    appname: service-registry-cluster
    hostname: localhost